version: "2"

services:
  mysql:
      container_name: mysql
      image: 192.168.29.158:5000/lnmp-mysql-alpine:latest
      #image: 192.168.29.158:5000/lnmp-mysql-jessie:latest
      ports:
        - "3307:3306"
      volumes:
        - ./data/mysql:/data/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 111111
  mongo:
      container_name: mongo
      image: 192.168.29.158:5000/lnmp-mongo-alpine:latest
      ports:
        - "27017:27017"
      volumes:
        - ./data/mongo:/data/db
  php_nginx:
      container_name: php_nginx
      image: 192.168.29.158:5000/lnmp-php-nginx-alpine:latest
      ports:
        - "80:80"
      links:
        - "mysql"
        - "mongo"
      #volumes_from:
      #  - mongo
      volumes:
        - ./data/php_nginx/log:/data/web/log